import type { Metadata } from "next";
import { Raleway} from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "@/Context/cartContext";
import ProvidersContainer from "@/components/ProvidersContainer/ProvidersContainer";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const myFont =Raleway({ weight:['100', '200','300','400','500','600','700','800','900'], subsets:['latin'] });

export const metadata: Metadata = {
  title: "Easy Mart App",
  description: "Generated by easy mart app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} antialiased`}
      >
        <ProvidersContainer>
          <CartContextProvider>
            <Navbar />
            {children}
            <Toaster position="bottom-right" />
            <Footer />
          </CartContextProvider>
        </ProvidersContainer>
      </body>
    </html>
  );
}
