import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "@/Context/cartContext";
import ProvidersContainer from "@/components/ProvidersContainer/ProvidersContainer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProvidersContainer>
          <CartContextProvider>
          <Navbar />
          {children}
          <Toaster position="bottom-right" />
        <Footer />
        </CartContextProvider>
        </ProvidersContainer>
      </body>
    </html>
  );
}
